version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: futbol-predict-db
    environment:
      POSTGRES_USER: futbol_user
      POSTGRES_PASSWORD: futbol_pass_2026
      POSTGRES_DB: prediccion_futbol
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futbol_user -d prediccion_futbol"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
